openapi: 3.0.0
info:
    description: Software Engineering Course STAD application
    version: 1.0.0
    title: STUD API
    contact:
        name: Kakandris Iasonas
        email: kiasonas@ece.auth.gr
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
    - url: https://4960fc6b-69ae-4b81-b305-78ea8d7a987f.mock.pstmn.io
    # The url: prefix is required localhost anti to milarakis.... .gr

paths:
    /admin/class/{className}:
        get:
            summary: get class info
            operationId: getClassInfoAdmin
            description: FR1 Ο καθηγητής και η γραμματεία πρέπει να μπορεί να επεξεργαστεί την τάξη
            parameters:
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Class"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        put:
            summary: change class info
            operationId: putClassInfoAdmin
            parameters:
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            requestBody:
                $ref: "#/components/requestBodies/Class"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Class"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
    /user/{userName}/class/{className}:
        get:
            summary: get class info
            operationId: getClassInfoUser
            description:  FR1 Ο καθηγητής και η γραμματεία πρέπει να μπορεί να επεξεργαστεί την τάξη
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Class"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        put:
            summary: change class info
            operationId: put Class Info user
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string

            requestBody:
                $ref: "#/components/requestBodies/Class"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Class"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
    /user/{userName}/class/{className}/chat:
        get:
            summary: get the chat of the classroom
            description: F2- Ο χρήστης θα πρέπει να έχει τη δυνατότητα να συνομιλήσει με τα υπόλοιπα μέλη της ‘τάξης’
            operationId: getClassChat
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Chat"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        post:
            summary: post a message to the classroom
            operationId: postClassMessage
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            requestBody:
                $ref: "#/components/requestBodies/NewMessage"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
    /user/{userName}:
        get:
            summary: get the user details
            description: FR-3 Ο χρήστης θα μπορεί να φτιάξει το προφίλ του
            operationId: getUserInfo
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
        put:
            summary: edit the user details
            operationId: editUserInfo
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
            requestBody:
                $ref: "#/components/requestBodies/User"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"

    /user/{userName}/class/{className}/grade:
        get:
            summary: get the grade of the user
            description: F4- Το σύστημα θα πρέπει να μπορεί να υπολογίσει τον μέσο όρο του μαθητή
            operationId: getUserGrade
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string
                - in: path
                  name: className
                  description: the name of the class
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Grade"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"
    /user/{userName}/notifications: 
        get: 
            summary: get the notifications of the user
            description: F5- Το σύστημα θα πρέπει να ειδοποιεί τον χρήστη για νέες ειδοποιήσεις
            operationId: getUserNotifications
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string            
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notifications"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"
    /user/{userName}/notifications/{notificationId}:
        get:
            summary: get a notification of the user using its id
            description: F5- Το σύστημα θα πρέπει να ειδοποιεί τον χρήστη για νέες ειδοποιήσεις
            operationId: getUserNotificationById
            parameters:
                - in: path
                  name: userName
                  description: the name of the user
                  required: true
                  schema:
                      type: string        
                - in: path
                  name: notificationId
                  description: the name id of the notification
                  required: true
                  schema:
                      type: integer   
                      format: int64   
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notification"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"  
    /admin/notifications:
        get:
            summary: get all the notifications
            description: F5- Το σύστημα θα πρέπει να ειδοποιεί τον χρήστη για νέες ειδοποιήσεις
            operationId: getAdminNotifications
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notifications"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"    
        post:
            summary: post a notification
            operationId: postNotification
            requestBody:
                $ref: "#/components/requestBodies/NewNotification"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notification"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"         
    /admin/notifications/{notificationId}:
        get:
            summary: get a certain notification
            description: F5- Το σύστημα θα πρέπει να ειδοποιεί τον χρήστη για νέες ειδοποιήσεις
            operationId: getAdminNotificationById
            parameters:      
                - in: path
                  name: notificationId
                  description: the name id of the notification
                  required: true
                  schema:
                      type: integer   
                      format: int64   
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notification"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"    
        put:
            summary: edit a certain notification
            description: F5- Το σύστημα θα πρέπει να ειδοποιεί τον χρήστη για νέες ειδοποιήσεις
            operationId: editAdminNotificationById
            parameters:      
                - in: path
                  name: notificationId
                  description: the name id of the notification
                  required: true
                  schema:
                      type: integer   
                      format: int64   
            requestBody:
                $ref: "#/components/requestBodies/NewNotification"
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Notification"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                               $ref: "#/components/schemas/Error"    
components:
    requestBodies:
        Class:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Class"
            description: Class model
            required: true
        NewMessage:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/NewMessage"
            description: message model
            required: true
        User:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/User"
            description: message model
            required: true
        NewNotification: 
            content: 
                application/json: 
                    schema: 
                        $ref: "#/components/schemas/NewNotification"
            description: notification model 
            required: true
    schemas:
        Class:
            type: object
            properties:
                className:
                    type: string
                users:
                    type: array
                    items:
                        $ref: "#/components/schemas/EnrolledUser"

        EnrolledUser:
            type: object
            properties:
                user:
                    $ref: "#/components/schemas/User"
                grade:
                    type: number

        User:
            type: object
            properties:
                userName:
                    type: string
                name:
                    type: string
                surname:
                    type: string
                email:
                    type: string
                id:
                    type: integer
                    format: int64
        Chat:
            type: array
            items:
                $ref: "#/components/schemas/Message"
        Message:
            allOf:
                - $ref: "#/components/schemas/NewMessage"
                - type: object
                  properties:
                      id:
                          type: integer
                          format: int64
        NewMessage:
            type: object
            properties:
                username:
                    type: string
                message:
                    type: string
        
        Grade: 
            type: object 
            properties: 
                username: 
                    type: string
                className: 
                    type: string 
                grade: 
                    type: number 

        Notifications: 
            type: array
            items: 
                $ref: "#/components/schemas/Notification"
        NewNotification: 
            type: object
            properties: 
                title: 
                    type: string 
                body: 
                    type: string 
        Notification:
            allOf: 
                - $ref: "#/components/schemas/NewNotification"
                - type: object
                  properties: 
                      id: 
                        type: integer
                        format: int64 
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                    format: int32
                message:
                    type: string
